#!/bin/sh


# path to search 
config="$HOME/.config"
note="$HOME/public/note"
script="$HOME/.local/usr"
code="$HOME/public/code"


# find all files under the path and send to skim
# if choose a file then edit with default editor
select=$(fd . -H --search-path $config \
            --search-path $note \
            --search-path $script \
            --search-path $code \
			--exclude ".oh-my-zsh" \
			--exclude ".note" \
            | sk --reverse --height 50%)

[ ! -z "$select" ] && $EDITOR $select
