#!/bin/dash

# Notice: this script need to be execute as root or with root permit


# get fan speed from command line, fan speed is percentage
fan_speed=$1 
[ -z "$fan_speed" ] && echo "need specify fan speed" && exit

# check manually gpu fan control enable or not, 1 is enabled
status=$(cat /sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable)

# enable gpu fan manually control
[ "$status" -eq 1 ] || echo "1" > /sys/class/drm/card0/device/hwmon/hwmon0/pwm1_enable

# change fan speed, convert percentage speed to real control number
speed_num=$((256 * $fan_speed / 100))
echo "$speed_num" > /sys/class/drm/card0/device/hwmon/hwmon0/pwm1
