#!/usr/bin/env bash

shopt -s nullglob globstar

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=bemenu
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" \
    --fn 'monospace 16' -H 40 -l 20 -i -p 'Copy Password: ')

[[ -n $password ]] || exit

pass show -c "$password" 2>/dev/null
