#!/bin/sh

# the script aims for rotating srceen for hyprland
# according to https://wiki.hyprland.org/Configuring/Monitors/
# rotate_srceen 90 (clock position 90 degrees)
# rotate_srceen -90 (reverse clock position)
# rotate_srceen 0 (return to normal)

# global define monitor name
# which can be find by: hyprctl monitors
# monitor=DP-1
info=$(hyprctl monitors -j | jq '.[] | select(.focused == true)')
monitor=$(echo $info | jq '.name' | tr -d '"')
width=$(echo $info | jq '.width')
height=$(echo $info | jq '.height')
refresh=$(echo $info | jq '.refreshRate')
positionX=$(echo $info | jq '.x')
positionY=$(echo $info | jq '.y')
scale=$(echo $info | jq '.scale')

rotate() {
    method=$1
    hyprctl keyword monitor $monitor,${width}x${height}@${refresh},${positionX}x${positionY},${scale},transform,$method
}

# accept argument of degrees
degree=${1:-0}

# to normal
if [ $degree -eq 0 ]; then
    rotate 3
# clock 90
elif [ $degree -eq 90 ]; then
    rotate 2
# clock -90
elif [ $degree -eq -90 ]; then
    rotate 0
else
    echo "Not a accept degrees! A accept one is 0/90/-90"
    exit 1
fi
