#!/bin/sh

# the script aims for rotating srceen for hyprland
# according to https://wiki.hyprland.org/Configuring/Monitors/
# rotate_srceen 90 (clock position 90 degrees)
# rotate_srceen -90 (reverse clock position)
# rotate_srceen 0 (return to normal)



# global define monitor name
# which can be find by: hyprctl monitors
monitor=DP-1

rotate () {
    monitor=$1
    method=$2
    hyprctl keyword monitor $monitor,2560x1440@60,0x0,1,transform,$method
}

# accept argument of degrees
degree=${1:-0}

if [ $degree -eq 0 ];then
    rotate $monitor 0
elif [ $degree -eq 90 ];then
    rotate $monitor 1
elif [ $degree -eq -90 ];then
    rotate $monitor 5
else
    echo "Not a accept degrees! A accept one is 0/90/-90"
    exit 1
fi

