#!/bin/sh
# only works for one single file/directory

PARAMETERS="$@"

flags="$(echo " $PARAMETERS" | rg -oe " -+\w+" | sed 's/^ //')"
name="$(echo " $PARAMETERS" | sed 's/ -.\w*//g' | sed 's/^ //')"

if [ -d "$name" -o -f "$name" ]; then
    formatname=$(echo "$name" | tr ' ' '_')
    cp -r "$name" /tmp/ &&
        rm $flags -I --one-file-system "$name" &&
        echo -e "\033[40;31m move $formatname to /tmp/ \033[0m"
fi
